[colors]
border               = "#1F153E"
directory_path       = "#00FFAA"
playback_speed       = "#FF5DC8"
currently_playing    = "#F1FF5D"
paused               = "#417BFF"
muted                = "#AE5DFF"
volume               = "#FF5D85"
separators           = "#00FFAA"
filesystem_directory = "#6B5DFF"
filesystem_file      = "#F98771"
highlight_color      = "#00EAFF"
