[colors]
border            = "#312A50"
artist            = "#FF5DC8"
title             = "#F1FF5D"
album             = "#00FFAA"
year              = "#00EAFF"
track_num         = "#5D92FF"
seekbar_filled    = "#00FFAA"
seekbar_unfilled  = "#000000"
status            = "#DDE1FF"
timestamp         = "#FF006A"
directory_path    = "#00FFAA"
playback_speed    = "#FF5DC8"
currently_playing = "#F1FF5D"
paused            = "#417BFF"
options           = "#AE5DFF"
volume            = "#FF5D85"
fs_directory      = "#6B5DFF"
fs_file           = "#F98771"
highlight_color   = "#00EAFF"

[directories]
music_directory = "/home/xygyl/Music"

[controls]
vol_delta = 2
