[colors]
album            = "#00FFAA"
artist           = "#FF5DC8"
border           = "#312A50"
fs_directory     = "#6B5DFF"
fs_file          = "#F98771"
highlight_color  = "#00EAFF"
options          = "#AE5DFF"
paused           = "#417BFF"
playback_speed   = "#FF5DC8"
seekbar_filled   = "#00FFAA"
seekbar_unfilled = "#000000"
status           = "#DDE1FF"
tab_selected     = "#6B5DFF"
tab_unselected   = "#000000"
timestamp        = "#FF006A"
title            = "#F1FF5D"
track_num        = "#5D92FF"
volume           = "#FF5D85"
year             = "#00EAFF"

[directories]
music_directory = "/home/xygyl/Music"

[controls]
vol_delta = 2
